Repository karczewskiPiotr/binar-games, pull requests merged in 2019-07, with the labels that each got.

#2 Switch from .erb to .haml
  Gemfile
  Gemfile.lock
  app/views/devise/confirmations/new.html.erb
  app/views/devise/confirmations/new.html.haml
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/confirmation_instructions.html.haml
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/email_changed.html.haml
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/password_change.html.haml
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.html.haml
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.haml
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/edit.html.haml
  app/views/devise/passwords/new.html.erb
  app/views/devise/passwords/new.html.haml
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/edit.html.haml
  app/views/devise/registrations/new.html.erb
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.erb
  app/views/devise/sessions/new.html.haml
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_error_messages.html.haml
  app/views/devise/shared/_links.html.erb
  app/views/devise/shared/_links.html.haml
  app/views/devise/unlocks/new.html.erb
  app/views/devise/unlocks/new.html.haml
  app/views/games/index.html.erb
  app/views/games/index.html.haml
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.haml
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.html.haml
  app/views/layouts/mailer.text.erb
  app/views/layouts/mailer.text.haml
Labels: enhancement

#4 Fixed routing for devise
  app/controllers/application_controller.rb
  config/routes.rb
Labels: hot-fix

#5 Main nav
  app/assets/javascripts/games.js
  app/assets/stylesheets/EpicMenu.css
  app/assets/stylesheets/games.scss
  app/controllers/application_controller.rb
  app/controllers/games_controller.rb
  app/helpers/games_helper.rb
  app/javascript/EpicMenu
  app/javascript/packs/EpicMenu.jsx
  app/javascript/packs/main-nav.jsx
  app/javascript/packs/profileAcces.jsx
  app/models/user.rb
  app/views/application/test.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/games/index.html.haml
  app/views/layouts/_main_nav.haml
  app/views/layouts/application.html.haml
  bell.png
  bin.png
  config/routes.rb
  package.json
  test/controllers/games_controller_test.rb
  yarn.lock
Labels: feature

#6 Fixed main-nav merge
  app/assets/javascripts/games.js
  app/assets/stylesheets/games.scss
  app/controllers/games_controller.rb
  app/helpers/games_helper.rb
  app/javascript/packs/main-nav.jsx
  app/views/games/index.html.haml
  test/controllers/games_controller_test.rb
Labels: hot-fix

#8 Setup Rspec tests environment
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  spec/controllers/.keep
  spec/factories/.keep
  spec/models/.keep
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/fixtures/files/.keep
  test/fixtures/users.yml
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/user_test.rb
  test/system/.keep
  test/test_helper.rb
Labels: enhancement

#10 Game model implementation and massive fixes
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/EpicMenu.css
  app/assets/stylesheets/application.scss
  app/controllers/categories_controller.rb
  app/controllers/games_controller.rb
  app/helpers/categories_helper.rb
  app/javascript/EpicMenu
  app/javascript/packs/EpicMenu.jsx
  app/javascript/packs/main-nav.jsx
  app/javascript/packs/profileAcces.jsx
  app/models/category.rb
  app/models/game.rb
  app/models/user.rb
  app/views/categories/_category.json.jbuilder
  app/views/categories/index.json.jbuilder
  app/views/categories/show.json.jbuilder
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/games/_errors.haml
  app/views/games/_form.haml
  app/views/games/_game.json.jbuilder
  app/views/games/edit.html.haml
  app/views/games/index.html.haml
  app/views/games/index.json.jbuilder
  app/views/games/new.html.haml
  app/views/games/show.html.haml
  app/views/games/show.json.jbuilder
  config/routes.rb
  db/migrate/20190710102221_create_games.rb
  db/migrate/20190711100950_create_categories.rb
  db/migrate/20190711111414_add_game_to_category.rb
  db/migrate/20190715073704_add_game_to_user.rb
  db/schema.rb
  spec/factories/games.rb
  spec/factories/users.rb
  spec/files/documents/dummy.pdf
  spec/files/images/avatar.png
  spec/models/game_spec.rb
  spec/models/user_spec.rb
Labels: feature

#12 User can see list of all games in GAMES tab
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/javascripts/events.js
  app/assets/stylesheets/EpicMenu.css
  app/assets/stylesheets/events/events.scss
  app/assets/stylesheets/games/index.scss
  app/assets/stylesheets/games/newgame.css
  app/assets/stylesheets/users/newlog.css
  app/assets/stylesheets/users/newsign.css
  app/assets/stylesheets/users/pass_forg.css
  app/assets/stylesheets/users/table.css
  app/controllers/api/v1/categories_controller.rb
  app/controllers/api/v1/games_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/api_controller.rb
  app/controllers/application_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/events_controller.rb
  app/controllers/games_controller.rb
  app/controllers/users_controller.rb
  app/javascript/components/games/Rating.jsx
  app/javascript/components/games/game.jsx
  app/javascript/components/games/star.jsx
  app/javascript/components/home.jsx
  app/javascript/packs/application.js
  app/javascript/packs/gamesList.jsx
  app/models/event.rb
  app/models/game.rb
  app/models/user.rb
  app/views/api/v1/categories/_category.json.jbuilder
  app/views/api/v1/categories/index.json.jbuilder
  app/views/api/v1/categories/show.json.jbuilder
  app/views/api/v1/games/_game.json.jbuilder
  app/views/api/v1/games/index.json.jbuilder
  app/views/api/v1/games/show.json.jbuilder
  app/views/api/v1/users/index.json.jbuilder
  app/views/application/test.html.haml
  app/views/categories/_category.json.jbuilder
  app/views/categories/index.json.jbuilder
  app/views/categories/show.json.jbuilder
  app/views/games/_game.json.jbuilder
  app/views/games/index.html.haml
  app/views/games/index.json.jbuilder
  app/views/games/show.json.jbuilder
  app/views/layouts/_main_nav.haml
  app/views/layouts/application.html.haml
  config/routes.rb
  db/migrate/20190719090710_add_default_to_rating_in_game.rb
  db/schema.rb
  spec/controllers/games_controller_spec.rb
  spec/factories/categories.rb
  spec/factories/games.rb
  spec/factories/users.rb
  spec/models/event_spec.rb
  spec/rails_helper.rb
  spec/views/api/v1/games/index_json_jbuilder_spec.rb
  spec/views/api/v1/games/show_json_jbuilder_spec.rb
Labels: feature

#24 Filter games
  app/assets/stylesheets/games/index.scss
  app/javascript/components/games/searchbar.jsx
  app/javascript/packs/gamesList.jsx
Labels: feature

#25 Layout fixes
  app/assets/stylesheets/alert_message.css
  app/assets/stylesheets/body_form.css
  app/assets/stylesheets/games/newgame.css
  app/assets/stylesheets/users/newlog.css
  app/assets/stylesheets/users/newsign.css
  app/assets/stylesheets/users/pass_forg.css
  app/assets/stylesheets/users/table.css
  app/javascript/components/table.jsx
  app/views/devise/passwords/new.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/games/show.html.haml
  app/views/layouts/devise.html.haml
Labels: hot-fix

#26 Filter games
  app/assets/stylesheets/games/index.scss
  app/javascript/components/games/filterDropdown.jsx
  app/javascript/components/games/searchbar.jsx
  app/javascript/packs/gamesList.jsx
  package.json
  yarn.lock
Labels: feature

#27 Sort games by title
  app/assets/stylesheets/games/index.scss
  app/javascript/components/games/sortButton.jsx
  app/javascript/packs/gamesList.jsx
Labels: feature

#28 Sort games
  app/javascript/components/games/sortButton.jsx
  app/javascript/packs/gamesList.jsx
Labels: feature

#29 Sort games by rating
  app/javascript/packs/gamesList.jsx
Labels: feature

#32 User can rate a game
  app/controllers/api/v1/games_controller.rb
  app/controllers/games_controller.rb
  app/javascript/components/games/Rating.jsx
  app/javascript/components/games/game.jsx
  app/javascript/components/games/gameDetails.jsx
  app/javascript/components/games/star.jsx
  app/javascript/packs/gamesList.jsx
  app/models/game.rb
  app/models/rating.rb
  app/models/user.rb
  app/views/api/v1/games/_game.json.jbuilder
  config/routes.rb
  db/migrate/20190725083002_rename_rating_to_global_rating.rb
  db/migrate/20190725083941_create_ratings_table.rb
  db/schema.rb
  spec/controllers/games_controller_spec.rb
  spec/models/game_spec.rb
  spec/rails_helper.rb
  spec/views/api/v1/games/index_json_jbuilder_spec.rb
  spec/views/api/v1/games/show_json_jbuilder_spec.rb
Labels: feature

#36 Revert "Favourites"
  app/assets/stylesheets/button.css
  app/controllers/api/v1/users_controller.rb
  app/javascript/components/table.jsx
  app/javascript/packs/users-table.jsx
  app/models/relationship.rb
  app/models/user.rb
  app/views/api/v1/users/following.json.jbuilder
  app/views/layouts/application.html.haml
  app/views/shared/_stats.html.haml
  app/views/users/show.html.haml
  config/routes.rb
  db/migrate/20190722115528_create_relationships.rb
  db/schema.rb
  serce.png
  serce.svg
  serduszeczko.svg
  serduszko.png
  spec/controllers/users_controller_spec.rb
  spec/factories/relationships.rb
  spec/models/relationship_spec.rb
  spec/models/user_spec.rb
  spec/views/api/v1/users/index_json_jbuilder_spec.rb
Labels: hot-fix

#35 Animations
  app/assets/stylesheets/games/animations.css
  app/javascript/components/games/game.jsx
  app/javascript/components/games/gameDetails.jsx
  app/javascript/packs/eventsList.jsx
  app/javascript/packs/gamesList.jsx
  package.json
  yarn.lock
Labels: feature
